# Generated by Django 6.0.4 on 2026-04-11 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='phone number')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP code')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register')], db_index=True, max_length=16, verbose_name='purpose')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OTP verification',
                'verbose_name_plural': 'OTP verifications',
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='otp_verific_phone_n_af56d7_idx')],
            },
        ),
    ]
