# Generated by Django 6.0.3 on 2026-04-11 09:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_unit_strings_to_fk(apps, schema_editor):
    Unit = apps.get_model("core", "Unit")
    Product = apps.get_model("core", "Product")
    # Historical Product still has CharField `unit` here.
    for p in Product.objects.all():
        raw = getattr(p, "unit", None)
        name = (raw or "").strip()[:50] or "Piece"
        u, _ = Unit.objects.get_or_create(name=name, defaults={"sort_order": 0})
        Product.objects.filter(pk=p.pk).update(unit_new_id=u.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_split_parent_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="name")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="sort order")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
                "db_table": "units",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="unit_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products_migrated",
                to="core.unit",
                verbose_name="unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                choices=[("flat", "Flat amount"), ("percentage", "Percentage")],
                default="flat",
                max_length=20,
                verbose_name="discount type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Flat: NPR off. Percentage: 0–100.",
                max_digits=10,
                null=True,
                verbose_name="discount value",
            ),
        ),
        migrations.RunPython(migrate_unit_strings_to_fk, noop_reverse),
        migrations.RemoveField(model_name="product", name="unit"),
        migrations.RenameField(model_name="product", old_name="unit_new", new_name="unit"),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.unit",
                verbose_name="unit",
            ),
        ),
    ]
