# Generated by Django 6.0.4 on 2026-04-11 10:07

from django.db import migrations, models


def _mark_existing_recipients_sent(apps, schema_editor):
    NotificationUser = apps.get_model("core", "NotificationUser")
    NotificationUser.objects.all().update(delivery_status="sent")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all_customers', 'All customers'), ('all_delivery_boys', 'All delivery partners'), ('all_users', 'All users')], default='all_customers', max_length=32, verbose_name='target audience'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16, verbose_name='delivery status'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='error message'),
        ),
        migrations.RunPython(_mark_existing_recipients_sent, _noop_reverse),
    ]
