# Generated by Django 6.0.4 on 2026-04-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_delivery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all_customers', 'All customers'), ('all_delivery_boys', 'All delivery partners'), ('all_users', 'All users (legacy broadcast)'), ('direct', 'Direct (selected recipients)')], default='all_customers', max_length=32, verbose_name='target audience'),
        ),
        migrations.CreateModel(
            name='StockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(db_index=True, verbose_name='purchase date')),
                ('invoice_reference', models.CharField(blank=True, max_length=120, null=True, verbose_name='invoice / reference')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount (NPR)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_purchases', to='core.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'stock purchase',
                'verbose_name_plural': 'stock purchases',
                'db_table': 'stock_purchases',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_kind', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], db_index=True, max_length=20, verbose_name='entry kind')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive adds to amount owed; negative is a payment or credit.', max_digits=12, verbose_name='amount (NPR)')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('stock_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='core.stockpurchase', verbose_name='stock purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'supplier ledger entry',
                'verbose_name_plural': 'supplier ledger entries',
                'db_table': 'supplier_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
