# Generated by Django 6.0.4 on 2026-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventory_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierledgerentry',
            name='stock_purchase',
        ),
        migrations.RemoveField(
            model_name='supplierledgerentry',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='driver_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='driver latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='driver longitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_distance_meters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='route distance (meters)'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='route duration (seconds)'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_polyline',
            field=models.TextField(blank=True, null=True, verbose_name='route polyline (encoded)'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_straight_fallback',
            field=models.BooleanField(default=False, verbose_name='straight-line route fallback'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tracking updated at'),
        ),
        migrations.DeleteModel(
            name='StockPurchase',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierLedgerEntry',
        ),
    ]
