# Generated by Django 6.0.4 on 2026-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_chat_customer_rider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderchatreceipt',
            new_name='order_chat__message_4b9722_idx',
            old_name='order_chat__message_6e4b2f_idx',
        ),
        migrations.AlterField(
            model_name='orderchatmessage',
            name='rider_staff',
            field=models.BooleanField(default=False, help_text='If true, only the assigned delivery partner and store staff see this message (not the customer).', verbose_name='rider–staff thread'),
        ),
    ]
