# Generated by Django 5.x migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_order_preorder_cartitem_is_preorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="banners/", verbose_name="image")),
                ("url", models.URLField(blank=True, max_length=500, verbose_name="link URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "db_table": "banners",
                "ordering": ["id"],
            },
        ),
    ]
