# Generated by Django 6.0.4 on 2026-05-20 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_order_guest_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersetting',
            name='delivery_under_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum delivery distance (km) from the store. 0 = no limit. Fee is always distance × delivery_charge_per_km.', max_digits=6, verbose_name='short delivery radius (km)'),
        ),
    ]
