"""
Django settings for fooddelivery project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6t@ddb=in!t=d)7)=*o+pxpk52jo%zt&lo$ivg6k8io7z=yevh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Required for cross-origin POSTs (e.g. SPA on :8080 → API on :8000) when CSRF checks Origin.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
]

AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Token auth does not require CSRF. SessionAuthentication forces CSRF on unsafe
# methods (including anonymous POST), which breaks cross-origin SPAs that never
# obtain Django's csrftoken cookie — hence "CSRF cookie not set" on /api/*.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Default is "format"; admin views use ?format=flat|tree for list shape, which
    # otherwise makes DRF filter renderers by format="flat" and raise Http404.
    'URL_FORMAT_OVERRIDE': 'api_format',
}
CORS_ALLOW_ALL_ORIGINS = True

# "console" logs OTP SMS; switch to your provider key in production.
SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "console")

# Twilio (set SMS_PROVIDER=twilio and these env vars for real SMS).
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")

# Firebase Cloud Messaging — legacy HTTP API server key (Project settings → Cloud Messaging).
FCM_SERVER_KEY = os.environ.get("FCM_SERVER_KEY", "")
# If true, log pushes only (no HTTP call); useful for local testing without keys.
FCM_DISABLE_SEND = os.environ.get("FCM_DISABLE_SEND", "").lower() in ("1", "true", "yes")

ROOT_URLCONF = 'fooddelivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fooddelivery.wsgi.application'
ASGI_APPLICATION = 'fooddelivery.asgi.application'

_redis_url = os.environ.get("REDIS_URL", "").strip()
if _redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_redis_url]},
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# Optional: log-only hook for SMS/email when recipients are offline (`core.chat_utils`).
CHAT_OFFLINE_NOTIFY = os.environ.get("CHAT_OFFLINE_NOTIFY", "").lower() in ("1", "true", "yes")
# Mirror staff chat replies to SMS when Twilio is configured (set to 0/false to disable).
CHAT_REPLY_SMS = os.environ.get("CHAT_REPLY_SMS", "1").lower() not in ("0", "false", "no")

# Server-side Directions API (optional; falls back to straight-line polyline if unset or failed).
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static')
] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom template admin panel at /admin/ (session login)
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/products/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Jazzmin (django-jazzmin) — admin theme
JAZZMIN_SETTINGS = {
    'site_title': 'Shyam Sweets Admin',
    'site_header': 'Shyam Sweets',
    'site_brand': 'Shyam Sweets',
    'welcome_sign': 'Food delivery control panel',
    'copyright': 'Shyam Sweets',
    'search_model': ['core.User', 'core.Order', 'core.Product', 'core.OTPVerification'],
    'topmenu_links': [
        {'name': 'Dashboard', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {
            'name': 'OTP Verification',
            'url': 'admin:core_otpverification_changelist',
            'permissions': ['core.view_otpverification'],
        },
    ],
    'icons': {
        'core.User': 'fas fa-user',
        'core.OTPVerification': 'fas fa-shield-alt',
        'core.Order': 'fas fa-shopping-bag',
        'core.Product': 'fas fa-utensils',
        'core.ParentCategory': 'fas fa-folder-open',
        'core.Category': 'fas fa-tag',
        'core.Cart': 'fas fa-shopping-cart',
        'core.Notification': 'fas fa-bell',
        'core.SuperSetting': 'fas fa-cog',
    },
    'order_with_respect_to': [
        'core.SuperSetting',
        'core.User',
        'core.OTPVerification',
        'core.ParentCategory',
        'core.Category',
        'core.Product',
        'core.Cart',
        'core.Order',
        'core.Notification',
    ],
}